version: '3.8'

services:
  dataset-processor:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./exports:/app/exports
      - ./data:/app/data
    environment:
      - CHAINLIT_HOST=0.0.0.0
      - CHAINLIT_PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
